// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfPjBUoTb4a59qYOLWq9-WWW5lfP8PnPA',
    appId: '1:218005664029:web:c7badaeb686e3187e731f4',
    messagingSenderId: '218005664029',
    projectId: 'silodom-app',
    authDomain: 'silodom-app.firebaseapp.com',
    storageBucket: 'silodom-app.firebasestorage.app',
    measurementId: 'G-SJE1FR5VWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmE-nRMrQkcdCiwx_XD2PI2wjWWb1q85A',
    appId: '1:218005664029:android:d10e72e57e2911a7e731f4',
    messagingSenderId: '218005664029',
    projectId: 'silodom-app',
    storageBucket: 'silodom-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGLLfy9lgvFD1RaEOh-u2rR48QTczeEU4',
    appId: '1:218005664029:ios:86caa09384d89ab5e731f4',
    messagingSenderId: '218005664029',
    projectId: 'silodom-app',
    storageBucket: 'silodom-app.firebasestorage.app',
    iosBundleId: 'com.silodom.app',
  );
}
